# Generated by Django 4.2.2 on 2023-08-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.CharField(max_length=11),
        ),
    ]
