# Generated by Django 4.2.2 on 2024-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=200)),
                ("test_logs", models.CharField(max_length=200)),
                ("test_status", models.CharField(max_length=200)),
            ],
        ),
    ]
